name: Data Refresh

on: 
 # push:
 #   branches: [main, master]
  schedule:  
    - cron: '0 21 * * 5'

jobs:
  update-data:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
      actions: write
      pages: write

    container: 
      image: mgaloto/scrapppython:02
    steps:
    - name: checkout_repo
      uses: actions/checkout@v3
      with: 
        ref: 'main'
    - name: Render Data
      run: bash ./bash/update_data.sh "MGaloto" "maxigaloto@hotmail.com"

