name: Data Refresh

on: 
  schedule:  
    - cron: '0 19,03 1,9,12,20,22 * *' # el dia 1,9,12, 20 y 25 del mes a las 18 y 18 hs arg
    # - cron:  '0 */12 * * *'
    # cada doce horas '0 */12 * * *'
    # cada 10 min '*/10 * * * *'


jobs:
  refresh-the-dashboard:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
      actions: write
      pages: write

    container: 
      image: mgaloto/scrapppython:01
    steps:
    - name: checkout_repo
      uses: actions/checkout@v3
      with: 
        ref: 'main'
    - name: Render Data
      run: bash ./bash/update_data.sh "MGaloto" "maxigaloto@hotmail.com"

